package com.drools.example

import com.drools.example.Career.Question;
import com.drools.example.Career.Answer;
import com.drools.example.Career.Solution
import java.sql.SQLOutput;

//STOP
rule "Solution"
    when
        Solution();
    then
        System.out.println("STOP");
end

//INITIAL QUESTION
rule "Q1"
	when
	then
	    Question question1 = new Question("Do you want a responsible job", 1);
//	    question1.setAnswer(Answer.YES);
		insert(question1);
		System.out.println(question1.questionText);
end

//Q1-YES
rule "Q2"
    when
        Question(index==1, answer==Answer.YES);
    then
        Question question2 = new Question("Marks higher than 60%", 2);
//        question2.setAnswer(Answer.NO);
        insert(question2);
		System.out.println(question2.questionText);
end

//Q1-NO
rule "Q1-sol"
    when
        Question(index==1, answer==Answer.NO);
    then
        Solution solution = new Solution("Become a hippie");
        insert(solution);
		System.out.println(solution.solutionText);
end

//Q2-YES
rule "Q3"
    when
        Question(index==2, answer==Answer.YES);
    then
        Question question3 = new Question("Willing to study hard", 3);
        insert(question3);
        System.out.println(question3.questionText);
end

//Q2-NO or Q8-NO or Q5-NO
rule "Q4"
    when
        Question((index==2 && answer==Answer.NO)
        || (index==8 && answer==Answer.NO)
        || (index==5 && answer==Answer.NO));
    then
        Question question4 = new Question("Want further schooling", 4);
//        question4.setAnswer(Answer.NO);
        insert(question4);
        System.out.println(question4.questionText);
end

//Q3-MAYBE
rule "Q3-sol"
    when
        Question(index==3, answer==Answer.MAYBE);
    then
        Solution solution = new Solution("Go to work for a year");
        insert(solution);
        System.out.println(solution.solutionText);
end

//Q3-NO or Q8-YES
rule "Q5"
    when
        Question((index==3 && answer==Answer.NO)||(index==8 && answer==Answer.YES));
    then
        Question question5 = new Question("Will it last", 5);
//        question5.setAnswer(Answer.NO);
        insert(question5);
        System.out.println(question5.questionText);
end

//Q3-YES
rule "Q6"
    when
        Question(index==3, answer==Answer.MAYBE);
    then
        Question question6 = new Question("Do you want to help society", 6);
        insert(question6);
        System.out.println(question6.questionText);
end

//Q4-YES
rule "Q7"
    when
        Question(index==4, answer==Answer.YES);
    then
        Question question7 = new Question("Interested in sciences", 7);
        insert(question7);
        System.out.println(question7.questionText);
end

//Q4-NO
rule "Q8"
    when
        Question(index==4, answer==Answer.NO);
    then
        Question question8 = new Question("Can you get a job", 8);
//        question8.setAnswer(Answer.YES);
        insert(question8);
        System.out.println(question8.questionText);
end

//Q5-YES
rule "Q5-sol"
    when
        Question(index==5, answer==Answer.YES);
    then
        Solution solution = new Solution("Continue as long as you can");
        insert(solution);
        System.out.println(solution.solutionText);
end

rule "Q9"
    when
        Question(index==6, answer==Answer.YES);
